apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eab-cert
  namespace: cert-manager
spec:
  secretName: acme-account-secret
  duration: 24h
  renewBefore: 2h
  commonName: pki.atlasqa.co.uk
  dnsNames:
  - pki.atlasqa.co.uk
  issuerRef:
    name: eab-issuer
